name: 'Commit Bitmap'
description: 'Commit the bitmap file after tag and export'
branding: 
  icon: 'git-commit'
  color: 'purple'
inputs:
  git-user-name:
    description: "Git user name"
    required: true
  git-user-email:
    description: "Git user email"
    required: true
  ws-dir:
    description: "Workspace json file directory path"
    required: false
  skip-push:
    description: "Skip commit push (for testing)"
    required: false
runs:
  using: 'node16'
  main: 'dist/index.js'
